title:            Gayathri Jaikumar
url:              http://gayajk.github.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-21332781-7
timezone:         
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
